### ISSUE TITLE
PS 1.7.6.x : Transporteur éronné

### ISSUE THREAD

**Issue by comxd** [PayboxByVerifone/PrestaShop#3]
Lors du paiement de la commande, lorsque celle-ci est enregistrée, le mode de transport enregistré n'est pas celui sélectionné par l'utilisateur.

Ce qui pose plusieurs problèmes :

1. impossible de savoir le transporteur originellement sélectionné par l'utilisateur
2. affichage de la confirmation de commande erronée (transporteur + montant total)
3. facture erronée (transporteur + montant total)
4. affichage de la commande pour le client erronée (transporteur + montant total)
5. BO : une alerte présente la commande comme partiellement payée (dans le cas d'un transporteur payant)

Exemple en BO pour une commande avec comme transporteur "retrait en magasin" (gratuit) :

![image](https://user-images.githubusercontent.com/9022239/94677595-782bbf80-031d-11eb-83cf-61ff448d46a6.png)

**Comment by jcpaybox** [comment]
Bonjour,

le mode d'intégration du module Verifone n'influence à priori pas le transporteur, je crains qu'ici le problème soit lié au mode de fonctionnement du module transport. le montant envoyé au paiement est le montant du panier lors du checkout, si il est erroné, cela pourrait être dû au module de transport.  un tel problème ne nous a à à ce jour pas été remonté.
Les logs de Prestashop pourraient peut être expliquer cette cinématique particulière, vous pourriez peut être contacter l'éditeur de ce module laposte ? n'hésitez pas à nous solliciter en cas de besoin.

cordialement,

verifone

**Comment by comxd** [comment]
Bonjour,

Effectivement le problème était ailleurs, merci pour votre retour rapide.

Cordialement,
David .D
